'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { FeatureCollection } from 'geojson';
import { buildSantaFeSvgMap, type BarrioData, type MapTheme } from '@/lib/mapSvg';

type Props = {
  barrios?: BarrioData[];
  theme?: MapTheme;
  width?: number;
  height?: number;
  className?: string;
};

export default function LocalidadMap({
  barrios = [],
  theme = 'dark',
  width = 860,
  height = 480,
  className = '',
}: Props) {
  const [geojson, setGeojson] = useState<FeatureCollection | null>(null);
  const [tooltip, setTooltip] = useState<{ x: number; y: number; text: string } | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetch('/geo/santafe-barrios.geojson')
      .then(r => r.json())
      .then(setGeojson)
      .catch(() => setGeojson(null));
  }, []);

  const svgString = useMemo(() => {
    if (!geojson) return '';
    return buildSantaFeSvgMap(geojson, { theme, width, height, barrios });
  }, [geojson, theme, width, height, barrios]);

  if (!svgString) {
    return (
      <div
        className={`flex items-center justify-center bg-fundesco-forest/10 rounded-xl ${className}`}
        style={{ width, height }}
        aria-label="Cargando mapa de Santa Fe"
      >
        <div className="w-8 h-8 border-4 border-fundesco-green border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className={`relative overflow-hidden rounded-xl ${className}`}
      style={{ width, height }}
    >
      {/* SVG map rendered inline for full control */}
      <div
        // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG is generated by our own pure function
        dangerouslySetInnerHTML={{ __html: svgString }}
        className="w-full h-full"
        aria-label="Mapa de barrios de la Localidad de Santa Fe, Bogotá D.C."
        role="img"
      />
      {tooltip && (
        <div
          className="pointer-events-none absolute z-10 rounded-lg px-2 py-1 text-xs shadow-lg"
          style={{
            left: tooltip.x + 8,
            top: tooltip.y - 30,
            background: theme === 'dark' ? 'rgba(22,33,24,0.95)' : 'rgba(255,255,255,0.95)',
            color: theme === 'dark' ? '#f0f9f0' : '#1a2e1a',
            border: '1px solid #178C72',
          }}
        >
          {tooltip.text}
        </div>
      )}
    </div>
  );
}
